site_name: Red Hat OpenShift Container Platform
repo_url: https://github.com/aireilly/openshift-docs
repo_name: openshift-docs
edit_uri: edit/main/

docs_dir: .

site_dir: ../public

exclude_docs: |
  **/drupal-build
  **/images
  **/modules
  **/snippets
  **/_attributes
  contributing_to_docs
  _stylesheets
  _topic_maps
  _templates
  scripts
  _javascripts

theme:
  name: material
  features:
  - content.code.copy
  - content.code.select
  - navigation.tracking
  - navigation.footer
  - navigation.top
  - navigation.instant
  - navigation.prune
  - palette.toggle
  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  logo: _mkdocs_assets/redhat.svg
  favicon: _mkdocs_assets/redhat-favicon.png

markdown_extensions:
  - markdown_gfm_admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang: en
      indexing: sections  # or: titles | full (default is full)
      separator: '[\s\-,:!=\[\]()/\"]+|(?!\b)(?=[A-Z][a-z])'
      pipeline:
        - stemmer         # Reduce words to stems
        - stopWordFilter  # Remove common words
        - trimmer         # Remove extra whitespace
      prebuild_index: true      # Build index at build time
      min_search_length: 3      # Minimum query length
      workers: 2  # Parallel processing
  - exclude-search:
      exclude:
        - modules/*
  - asciidoctor_backend:
      edit_includes: true
      fail_on_error: false
      ignore_missing: true
      safe_mode: safe
      attributes:
        product-title: OpenShift Container Platform
        product-version: 4.19
        imagesdir: images
        showtitle: true
        sectanchors: true
        sectlinks: true
        icons: font
        idprefix: ""
        idseparator: "-"
        outfilesuffix: .html
        source-highlighter: rouge
        "!toc": "" # Unset the page TOC
